In [ ]:
import pandas as pd
import numpy as np
%matplotlib inline
import otter
grader = otter.Notebook()

# A2 | Week 1: Practice For Loops & Dictionary

------

### Instructions:

- Complete 50 points worth of questions to pass the assessment
  - You can attempt any number of questions and in any order provided you pass at least 50 points.
- Develop and check your answers in the spaces provided.
  - Do not remove any variables other provided markings already present in the answer spaces.
  - Do not make any changes to this notebook outside of the answer spaces provided.
  
#### Submitting

- Upload your .ipynb file to Gradescope (Make sure to restart the kernel and run all before you submit)
- You can submit as many times as needed
- When reviewing results, ignore any results listed under "Public Tests"

For more information, see the assessment page. We have also provided an example question below for clarity. 

#### Example Question
Write a Python program to display the elements in the list `[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]` using for loops. Create the variable `example_output` and use it inside the for loop to construct the string that you want to display at the end of the program.

```
#This solution is for demonstration purposes ONLY. 
#There may be other ways of doing this task using for loops that produce the same output.
#You have the freedom to use a solution that you prefer as long as it uses for loop and 
#produces the expected output using the example_output variable.
example_output = ""
example_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
for i in example_list:
    example_output += str(i)
    example_output += "\n"
example_output = example_output.strip() #this is to remove the extra new line in 10
print(example_output)
```

#### Question 1&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(1 Point)
Create a list `q1_list` and add the following names to it: *Lisa, Dave, Sage, Emma, John, David*. Write a Python program to display names using a for loop in the following format: `Hello! "NAME"` (*Note: NAME should be replaced with the name in the list in each iteration*). Create the variable `output1` and use it inside the while loop to construct the string that you want to display at the end of the program.

Expected Output:  

Hello! "Lisa"  
Hello! "Dave"  
Hello! "Sage"  
Hello! "Emma"  
Hello! "John"  
Hello! "David"

In [126]:
output1 = ""

# Write your solution here
q1_list = ['Lisa', 'Dave', 'Sage', 'Emma', 'John', 'David']
for item in q1_list:
    output1 += f'Hello! "{item}"\n'
    
output1 = output1.rstrip()
print(output1)

Hello! "Lisa"
Hello! "Dave"
Hello! "Sage"
Hello! "Emma"
Hello! "John"
Hello! "David"


#### Question 2&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(1 Point)
Create a list `q2_list` and add the following numbers to it: *1, 2, 6, 10, 19, 21*. Write a Python program to display the square of each number using a for loop in the following format: `The square of NUMBER is SQUARENUM!` (*Note: NUMBER and SQUARENUM should be replaced with the number in the list in each iteration and the square of it*). Create the variable `output2` and use it inside the for loop to construct the string that you want to display at the end of the program.

*Note: The displayed string should be in the same format as in Q1. For clarity, the expected output is shown below.*

Expected Output:
<p>
The square of 1 is 1!<br>
The square of 2 is 4!<br>
The square of 6 is 36!<br>
The square of 10 is 100!<br> 
The square of 19 is 361!<br>
The square of 21 is 441!
</p>

In [125]:
output2 = ""

# Write your solution here
q2_list = [1, 2, 6, 10, 19, 21]
for item in q2_list:
    squarenum = item**2
    output2 += f'The square of {item} is {squarenum}!\n'
    
output2 = output2.rstrip()
print(output2)


The square of 1 is 1!
The square of 2 is 4!
The square of 6 is 36!
The square of 10 is 100!
The square of 19 is 361!
The square of 21 is 441!


#### Question 3&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(1 Point)
Write a Python program to iterate through the string `q3_txt = "PyThoN"` and displays every letter in upper-case using a for loop. Create the variable `output3` and use  it inside the for loop to construct the string that you want to display at the end of the program.

*Note: The displayed string should be in the same format as in Q1. For clarity, the expected output is shown below.*

Expected Output:
<p>
P<br>
Y<br>
T<br>
H<br>
O<br>
N
</p>

In [120]:
output3 = ""

# Write your solution here
q3_txt = "PyThoN"
for item in q3_txt:
    output3 += item.upper() + "\n"
    
output3 = output3.rstrip()
print(output3)


P
Y
T
H
O
N


#### Question 4&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(1 Point)
Write a Python program to iterate through the string `q4_txt = "Python is My favorite programming language. It is also famous for its simple programming syntax, code readability and English-like commands that make coding in Python lot easier and efficient."` and find the count of letter `m` using a for loop (make sure that you lower-case the string to calculate all `m`s in it). Use the counter variable `output4` for the calculations needed.

In [117]:
output4 = ""

# Write your solution here
output4 = 0
q4_txt = "Python is My favorite programming language. It is also famous for its simple programming syntax, code readability and English-like commands that make coding in Python lot easier and efficient."
for item in q4_txt:
    if (item.lower() == "m"):
        output4 += 1
        
print(output4)

10


#### Question 5&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(1 Point)
Create a list `q5_list` and add the following numbers to it: *-12, 20, -91, 90, -19, 39*. Write a Python program to display numbers in the list that are both postive and even using a for loop. Create the variable `output5` and use it inside the for loop to construct the string that you want to display at the end of the program.

*Note: The displayed string should be in the same format as in Q1.*

In [116]:
output5 = ""

# Write your solution here
q5_list = [-12, 20, -91, 90, -19, 39]
for item in q5_list:
    if (item > 0 and item % 2 == 0):
        output5 += str(item) + "\n"
        
output5 = output5.rstrip()
print(output5)


20
90


#### Question 6&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(3 Points)
Create a list `q6_list` with the following items to it: *1, Emma, 6, John, David, 21, 19, Dave*. Create two empty lists `output6_numbers` and `output6_names`. Write a Python program that loops through `q6_list` and perform the folowing:
* if a number is encountered, add it to `output6_numbers`
* if a name (i.e., a string) is encountered add it to `output6_names`

***
<details>
  <summary><span style="color:blue">Click to see Hints</span></summary>
    
* You will need to use string methods such as isdigit() and isalpha() to identify whether it is a number or a name.
</details>

In [115]:
# Write your solution here
q6_list = [1, 'Emma', 6, 'John', 'David', 21, 19, 'Dave']
output6_names = []
output6_numbers = []
for item in q6_list:
    if (type(item) == int):
        output6_numbers.append(item)
    else:
        output6_names.append(item)
        
print(output6_numbers)
print(output6_names)


[1, 6, 21, 19]
['Emma', 'John', 'David', 'Dave']


#### Question 7&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(3 Points) 
Write a Python program to display the following pattern using for loops. Create the variable `output7` and use it inside the while loop to construct the string that you want to display at the end of the program.

<p>
1<br> 
1 2<br>
1 2 3<br> 
1 2 3 4<br>
1 2 3 4 5<br>
</p>

In [127]:
output7 = ""

# Write your solution here
i = 1
while (i <= 5):
    j = 1
    while (j <= i):
        output7 += str(j) + " "
        j += 1
    output7 = output7.rstrip()
    output7 += "\n"    
    i += 1
output7 = output7.rstrip()

print(output7)


1
1 2
1 2 3
1 2 3 4
1 2 3 4 5


#### Question 8&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(3 Points) 
Create a list `q8_list = [1, 3.1, ["John", "David"], 19, 30, "Python", 9.1, "Java", 12.1212, "Go", -1.2, ".NET", 9, [-1.2, 1.0], -9, [1, 2]]`. Create an empty list `output8_ints`. Write a Python program that loops through `q8_list` and append only integer numbers to `output8_ints`.

In [110]:
# Write your solution here
q8_list = [1, 3.1, ["John", "David"], 19, 30, "Python", 9.1, "Java", 12.1212, "Go", -1.2, ".NET", 9, [-1.2, 1.0], -9, [1, 2]]
output8_ints = []

for item in q8_list:
    if (type(item) == int):
        output8_ints.append(item)
        
print(output8_ints)

[1, 19, 30, 9, -9]


#### Question 9&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(3 Points)
Write a Python program to display the Fibonacci series up to 10 terms. The next number in Fibonacci series is found by adding up the two numbers before it. The first two numbers are 0 and 1. For example, in the Fibonacci series: 0, 1, 1, 2, 3, 5, 8, the next number is calculated as 5+8 = 13. Use a for loop with variables `q9_num1` and `q9_num2` to store first and second numbers of the series. Create the variable `output9` and use it inside the for loop to construct the string that you want to display at the end of the program.

*Note: The displayed string should be in the same format as in Q1.*

In [109]:
output9 = ""

# Write your solution here
q9_temp = ['0', '1']
for i in range(2, 10):
    number = int(q9_temp[i-1]) + int(q9_temp[i-2])
    q9_temp.append(str(number))

output9 = "\n".join(q9_temp)
print(output9)

0
1
1
2
3
5
8
13
21
34


#### Question 10&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(3 Points)
Write a Python program to convert the following two lists into a dictionary called `output10`.
```
q10_keys = ["John", "Danise", "David", "Kelly", "Emma", "Olivia"]
q10_values = [12, 10, 9, 19, 30, 33]
```

In [103]:
output10 = {}

# Write your solution here
q10_keys = ["John", "Danise", "David", "Kelly", "Emma", "Olivia"]
q10_values = [12, 10, 9, 19, 30, 33]
for i in range(len(q10_keys)):
    output10[q10_keys[i]] = q10_values[i]
    
print(output10)


{'John': 12, 'Danise': 10, 'David': 9, 'Kelly': 19, 'Emma': 30, 'Olivia': 33}


#### Question 11&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(4 Points)
Write a Python program to display the following pattern using for loops. Create the variable `output11` and use it inside the while loop to construct the string that you want to display at the end of the program.
<p>
5 4 3 2 1<br> 
4 3 2 1<br> 
3 2 1<br> 
2 1<br>
1<br>
</p>

In [128]:
output11 = ""

# Write your solution here
for i in range(5, 0, -1):
    for j in range(i, 0, -1):
        output11 += str(j) + " "
    output11 = output11.rstrip()
    output11 += "\n"

output11 = output11.rstrip()
print(output11)

5 4 3 2 1
4 3 2 1
3 2 1
2 1
1


#### Question 12&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(4 Points)
Write a Python program to display the following pattern using for loops. Create the variable `output12` and use it inside the while loop to construct the string that you want to display at the end of the program.
<p>
* <br>
* * <br>
* * * <br>
* * * * <br>
* * * * * <br>
* * * * <br>
* * * <br>
* * <br>
*
</p>

In [129]:
output12 = ""

# Write your solution here
q12_temp = []
for i in range(1, 6):
    q12_temp_line = "* "*i
    q12_temp_line = q12_temp_line.rstrip()
    q12_temp.append(q12_temp_line + "\n")

output12 += "".join(q12_temp)

q12_temp.pop()
q12_temp.reverse()
output12 += "".join(q12_temp)
output12 = output12.rstrip()

print(output12)


*
* *
* * *
* * * *
* * * * *
* * * *
* * *
* *
*


#### Question 13&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(4 Points)
Write a Python program to concatenate following dictionaries to create a new dictionary called `output13`.
```
q13_1 = {1:10, 2:20, 3:30}
q13_2 = {4:40, 5:50}
q13_3 = {6:60, 7:70, 8:80}
q13_4 = {9:90}
```

In [93]:
output13 = {}

# Write your solution here
q13_1 = {1:10, 2:20, 3:30}
q13_2 = {4:40, 5:50}
q13_3 = {6:60, 7:70, 8:80}
q13_4 = {9:90}

q13_temp = [q13_1, q13_2, q13_3, q13_4]
for item in q13_temp:
    output13.update(item)
print(output13)

{1: 10, 2: 20, 3: 30, 4: 40, 5: 50, 6: 60, 7: 70, 8: 80, 9: 90}


#### Question 14&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(4 Points)
Write a Python program that filters odd and even numbers from the following list: `q14_list = [19, 21, 2, 6, 26, 26, 39, 91, 93, 33, 12, 19, 31, 30]`. Create two empty lists: `output14_odd` and `output14_even` and append odd and even numbers respectively from the elements in `q14_list`.

In [91]:
# Write your solution here
q14_list = [19, 21, 2, 6, 26, 26, 39, 91, 93, 33, 12, 19, 31, 30]
output14_odd = []
output14_even = []
for item in q14_list:
    if (item % 2 == 0):
        output14_even.append(item)
    else:
        output14_odd.append(item)
        
print(output14_odd)
print(output14_even)


[19, 21, 39, 91, 93, 33, 19, 31]
[2, 6, 26, 26, 12, 30]


#### Question 15 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(4 Points) 
Write a Python program to display the following pattern using for loops. Create the variable `output15` and use it inside the while loop to construct the string that you want to display at the end of the program.
<p>
1 2 3 4 5<br>
2 2 3 4 5<br> 
3 3 3 4 5<br> 
4 4 4 4 5<br> 
5 5 5 5 5<br>
</p>

In [133]:
output15 = ""

# Write your solution here
for i in range(1, 6):
    line = ""
    for j in range(1, 6):
        if (j <= i):
            line += str(i) + " "
        else:
            line += str(j) + " "
    line = line.rstrip()
    line = line + "\n"
    output15 += line

output15 = output15.rstrip()
print(output15)


1 2 3 4 5
2 2 3 4 5
3 3 3 4 5
4 4 4 4 5
5 5 5 5 5


#### Question 16 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(4 Points)
Write a Python program to multiply all the items in the following dictionary using for loops (i.e., $12*10*9*19*30*33$). Create the variable `output16` and assign the solution to it.
```
q16_d = {'John': 12, 'Danise': 10, 'David': 9, 'Kelly': 19, 'Emma': 30, 'Olivia': 33}
```

In [83]:
# Write your solution here
q16_d = {'John': 12, 'Danise': 10, 'David': 9, 'Kelly': 19, 'Emma': 30, 'Olivia': 33}
output16 = 1
for v in q16_d.values():
    output16 *= v
    
print(output16)


20314800


#### Question 17 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(6 Points)
 Write a Python program to calculate factorial of an integer number using a for loop. Create a variable `q17_input` and assign the number 131 to it. To calculate the factorial use the following guidelines. Create a variable `output17` and assign the factorial of it.

* Factorial of number n is represented by `n!` and it is equal to `1*2*3*....*(n-1)*n`. For example, `4!` = `1*2*3*4` = 24
* Note that 1! = 1 and 0! = 1

In [81]:
q17_input = 131

# Write your solution here
output17 = 1

if (q17_input != 0):
    for i in range(1,q17_input + 1):
        output17 *= i
        
print(output17)

847158069087882051098456875815279568163352087665474498775849754305766436915303927682164623187034167333264599970492141556534816949699515865660644961729169613882287309922474300878212776434073600000000000000000000000000000000


#### Question 18 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(6 Points)
Given the following two dictionaries, write a Python program to combine two dictionary adding values for common keys. Create an empty list `output18` and assign the new dictionary to it.
```
q18_d1 = {'x': 120, 'y': 200, 'z':300, 'w': 30}
q18_d2 = {'x': 90, 'y': 120, 'z':300, 'm': 120}
```

In [77]:
# Write your solution here
q18_d1 = {'x': 120, 'y': 200, 'z':300, 'w': 30}
q18_d2 = {'x': 90, 'y': 120, 'z':300, 'm': 120}
output18 = {}

for k, v in q18_d1.items():
    if (k in q18_d2):
        output18[k] = v + q18_d2[k]
    else:
        output18[k] = v
        
for k, v in q18_d2.items():
    if (k not in q18_d1):
        output18[k] = v
print(output18)

{'x': 210, 'y': 320, 'z': 600, 'w': 30, 'm': 120}


#### Question 19 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(6 Points)
Given the following dictionary, write a Python program to identify all unique values in it and append them in to a list called `output19`.
```
q19_d = {112:'dog', 113:'cat', 119:'dog', 120:'dog', 126:'parrot', 130:'duck', 131:'dog', 133:'cat', 136:'duck', 139:'parrot'}
```

In [75]:
output19 = []

# Write your solution here
q19_d = {112:'dog', 113:'cat', 119:'dog', 120:'dog', 126:'parrot', 130:'duck', 131:'dog', 133:'cat', 136:'duck', 139:'parrot'}
for v in q19_d.values():
    if v not in output19:
        output19.append(v)
        
print(output19)

['dog', 'cat', 'parrot', 'duck']


#### Question 20 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(6 Points)
Given the following list, write a Python program to convert it into a nested dictionary of keys called `output20`.
```
q20_list = ['John', 'Danise', 'David', 'Kelly']
```
The expected output of `output20` is `{'John': {'Danise': {'David': {'Kelly': {}}}}}`

In [74]:
# Write your solution here
q20_list = ['John', 'Danise', 'David', 'Kelly']
output20 = {}
q20_temp = []

for i in range(len(q20_list)):
    q20_temp.append(dict())

for i in range(len(q20_list)-1, -1, -1):
    value = q20_list[i]
    if (i == len(q20_list)-1):
        q20_temp[i][value] = {}
    else:
        q20_temp[i][value] = q20_temp[i+1]
    
output20 = q20_temp[0].copy()

print(output20)


{'John': {'Danise': {'David': {'Kelly': {}}}}}


#### Question 21 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(6 Points)
Given the disctionary `output21 = {'x': 120, 'y': 200, 'z':300, 'w': 30}`, write a Python program to replace its values with their average using the below dis=ctionary.
```
q21_d = {'x': 90, 'y': 140, 'z':120, 'm': 120}
```
The expected output of `output21` will be in the following format: `{'x': 105, 'y': 170, 'z': 210, 'w': 30}`

In [44]:
output21 = {'x': 120, 'y': 200, 'z':300, 'w': 30}

# Write your solution here

q21_d = {'x': 90, 'y': 140, 'z':120, 'm': 120}

for k in output21.keys():
    if (k in q21_d):
        output21[k] = (output21[k] + q21_d[k]) // 2
print(output21)

{'x': 105, 'y': 170, 'z': 210, 'w': 30}


#### Question 22 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(6 Points)
Given the following list of dictionaries in `output22`, change the values of the dictionaries based on the length of its corresponding key.
```
output22 = {{"John": 0, "Danise": 0, "Kelly": 0}, {"Python": 0, "Java": 0}, {"Toy": 0}, {"Apple": 0, "Grapes": 0}}
```
The expected output of `output22` will be in the following format: `[{'John': 4, 'Danise': 6, 'Kelly': 5}, {'Python': 6, 'Java': 4}, {'Toy': 3}, {'Apple': 5, 'Grapes': 6}]`

In [42]:
# Write your solution here
output22 = [{"John": 0, "Danise": 0, "Kelly": 0}, {"Python": 0, "Java": 0}, {"Toy": 0}, {"Apple": 0, "Grapes": 0}]
for item in output22:
    for k in item.keys():
        item[k] = len(k)
        
print(output22)

[{'John': 4, 'Danise': 6, 'Kelly': 5}, {'Python': 6, 'Java': 4}, {'Toy': 3}, {'Apple': 5, 'Grapes': 6}]


#### Question 23 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)
Write a Python program to display the following pattern (letter `M`) using for loops. Create the variable `output23` and use it inside the while loop to construct the string that you want to display at the end of the program.
```
        * 
       * * 
      * * * 
     * * * * 
    * * * * * 
   * * * * * * 
    * * * * * 
     * * * * 
      * * * 
       * * 
        *
```

In [131]:
output23 = "" 

# Write your solution here
q23_max_wildcards = 6
q23_base_length = q23_max_wildcards
temp = []
line = 1
while (line <= 6):
    max_length = line + q23_base_length 
    temp_line = "   " + " " * (max_length - line*2) + ("* " * line)
    temp_line = temp_line.rstrip()
    temp.append(temp_line + "\n")
    line += 1
    
output23 += "".join(temp)
temp.pop()
temp.reverse()
output23 += "".join(temp)

output23 = output23.rstrip()
print(output23)


        *
       * *
      * * *
     * * * *
    * * * * *
   * * * * * *
    * * * * *
     * * * *
      * * *
       * *
        *


#### Question 24 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)
Write a Python program to display the following pattern using while loops. Create the variable `output24` and use it inside the while loop to construct the string that you want to display at the end of the program.
```
5*4*3*2*1*1*2*3*4*5*

5*4*3*2*****2*3*4*5*

5*4*3*********3*4*5*

5*4*************4*5*

5*****************5*

********************
```

In [134]:
output24 = ""

# Write your solution here
q24_max = 5
q24_count = q24_max
q24_line = 1

while(q24_line <= q24_max + 1):
    temp = ""
    q24_count = q24_max
    while(q24_count > 0):
        if (q24_count >= q24_line):
            temp += f'{q24_count}*'
        else:
            temp += '**'
        q24_count -= 1
    
    temp += temp[len(temp)-2::-1]
    output24 += temp + "*\n\n"
    
    q24_line += 1

output24 = output24.rstrip()
print(output24)

5*4*3*2*1*1*2*3*4*5*

5*4*3*2*****2*3*4*5*

5*4*3*********3*4*5*

5*4*************4*5*

5*****************5*

********************
